matrix:
  include:
    - language: c
      sudo: true
      install:
        #- set -v
        - git clone https://github.com/CWRU-AutonomousVehiclesLab/ros-arduino-lib
        - rm -rf ros-arduino-lib/ros_lib/examples
        - rm -rf ros-arduino-lib/ros_lib/tests
        - export ARDUINO_IDE_VERSION="1.8.10"
        - wget --quiet https://downloads.arduino.cc/arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz
        - mkdir $HOME/arduino_ide
        - tar xf arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz -C $HOME/arduino_ide/ 
        - cp -r ros-arduino-lib/ros_lib $HOME/arduino_ide/arduino-1.8.10/libraries/
        - curl -fsSL https://www.pjrc.com/teensy/td_148/TeensyduinoInstall.linux64 -o TeensyduinoInstall.linux64
        - sudo chmod +x TeensyduinoInstall.linux64
        - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
        - sleep 3
        - export DISPLAY=:1.0
        - ./TeensyduinoInstall.linux64 --dir=$HOME/arduino_ide/arduino-$ARDUINO_IDE_VERSION
        
      script:
       - source build-sketches.sh

notifications:
  email:
    recipients:
      - chude.qian@case.edu
      - flm@case.edu
    on_success: always
    on_failure: always

    slack:
      rooms:
      - cwruavl:c8BfLwvtO7uK1Ogn2vNLmAro#travis-reporter
      - cwruavl:c8BfLwvtO7uK1Ogn2vNLmAro#project-milou
      - flm@case.edu
      on_success: always
      on_failure: always